# Generated by Django 4.0.6 on 2022-08-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0003_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
