# Generated by Django 4.0.6 on 2022-08-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0004_alter_comentarios_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='cuerpo_comentario',
            field=models.TextField(verbose_name=''),
        ),
    ]
